/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
#include <cmath>
int main()
{
    int max_num{4'000'000};
    int fib1{1};
    int fib2{1};
    int fib3{};
    int sum_total{0};

    do
    {
        fib3 = fib1 + fib2;
        if ((fib3/2)*2 == fib3) sum_total += fib3;
        fib1 = fib2;
        fib2 = fib3;
    } while (fib2 < max_num);

    std::cout << sum_total;
    
}