/* 
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

#include "UsefulFunctions.h"

int triangle(int n)
{
    return n * (n + 1) / 2;
}
int pentagonal(int n)
{
    return n * (3 * n - 1) / 2;
}
int hexagonal(int n)
{
    return n * (2 * n - 1);
}

int main()
{
    int a{2};
    int b{2};
    int c{2};

    int Ta{3};
    int Pb{5};
    int Hc{6};

    bool found{false};

    while (true)
    {
        // std::cout << Ta << ", " << Pb << ", " << Hc << "\n";
        // std::cin.get();
        if (Ta == Pb && Pb == Hc && a != 285)
        {
            std::cout << a << ", " << b << ", " << c << "\n";
            std::cout << "Ta = " << Ta << "\n";
            break;
        }

        if (Ta <= Pb && Ta <= Hc)
        {
            Ta += a + 1;
            ++a;
        }
        else if (Pb <= Ta && Pb <= Hc)
        {
            Pb += 3 * b + 1;
            ++b;
        }
        else if (Hc <= Ta && Hc <= Pb)
        {
            Hc += 4 * c + 1;
            ++c;
        }
    }
    return 0;
}